### ISSUE TITLE
One band / BPM Trim lfo

### ISSUE THREAD

**Issue by Amy-Triptyline** [Coirt/Bark#16]
1. One Band module : When a modulation source is connected to the frequency dial CV input, regardless of it's range, the lowest value of the modulated frequency range will not go below roughly 350Hz. 

2. On the BPM Trim LFO : When making an adjustment to the tempo it snaps to values either double upwards or half downwards, restricting the user to 30bpm, 60bpm ,120bpm, 240bpm. etc.

**Comment by Coirt** [comment]
The lowest value will be 220Hz this is by design, modulating lower values can be unstable and cause undesirable effects.

The BPM snapping is also by design. Double/Half the BPM value keeps the tempo in sync. You are not restricted to the value displayed, there is more than 7 knobs on the module ;-)

**Comment by DraGonas79** [comment]
1. Ah, I see.
2. Oh ok, so a constant voltage from another module to an FM CV input and adjust accordingly for desired bpm. (a constant voltage from one of the trim section dials outs obviously works for this but means it's no longer free for making the trim output wave adjustments). Unless I'm missing something.

**Comment by Coirt** [comment]
You could do it that way but there is dedicated parameters for fine tuning the BPM or Hz values, Have you tried all knobs? It's an Easter Egg... All I can say is there is 2 extra knobs on the BPM module and 1 on the Hz module.

**Comment by DraGonas79** [comment]
Oh Jesus, that's brilliant haha nice one! :) Has this already been asked in the facebook group or the forum?

**Comment by Coirt** [comment]
Nope you're the first!

**Comment by Coirt** [comment]
It may be easier to find those hidden knobs in v1
