### ISSUE TITLE
VCV Browser Crash

### ISSUE THREAD

**Issue by midiguru** [Coirt/Bark#22]
I have just updated three plugins (Ohmer, Bidoo, and Coirt/Bark) in VCV for Windows. The VCV browser now crashes consistently when opened. I don't know which plugin is doing this, so I will need the _previous_ version of your Windows plugin in order to test it. Please advise where I can download that. Thanks!

**Comment by midiguru** [comment]
It's the Bidoo plugin. Never mind.

**Comment by Coirt** [comment]
Thanks for the report anyway!
