### ISSUE TITLE
FR Red/Green Lights on Poly X open/mute

### ISSUE THREAD

**Issue by Petervos2018** [Coirt/Bark#24]
Hi Phil,
Love your modules , right now I am using Poly X to mute channels inside a poly cable , which is AWESOME !
Only thing is I can't really see which channels I've muted or opened.
I changed the svg files and now they look like this. 
And it's easy to see which one is muted and which one is open.
Tell me what you think. Too ugly ?
![Bark Poly X MuteOpen](https://user-images.githubusercontent.com/46076474/62826192-87026080-bbb7-11e9-9f8d-342ce18f76d3.jpg)

Greetings Peter.

**Comment by Coirt** [comment]
Hi Peter thanks for the feedback. The only thing is it will change the buttons on clamp also. I will look into refining the button some more, because it is so small it is hard to keep detail and make it stand out. The tooltip value will also show the buttons state when moused over.

**Comment by Petervos2018** [comment]
> it will change the buttons on clamp also

Ah, I didn't see/think of that

> The tooltip value will also show the buttons state when moused over

True, but with the coloured lights I can see all the channels at once, immediately, and from a (small) distance. 

Thanks for replying, greetings
Peter.

**Comment by Coirt** [comment]
Could you try these, tell me what you think.

[PolyXTestButton.zip](https://github.com/Coirt/Bark/files/3490114/PolyXTestButton.zip)

You can copy them to the res folder and overwrite what is there. Move the ones you did first if you want to keep.

**Comment by Petervos2018** [comment]
At 100% scale/zoom it's still hard to see, at 150% they look nice, subtle but nice.

**Comment by Coirt** [comment]
Added in ded25be
