### ISSUE TITLE
Rack 2

### ISSUE THREAD

**Issue by pgatt** [Coirt/Bark#32]
Hi Phil, I use Trim LFO fairly frequently - wondering if you will be updating your modules to VCV2?
Thanks,
Paul

**Comment by Coirt** [comment]
Sure

**Comment by pgatt** [comment]
Awesome! Thanks, and looking forward to it!

**Comment by Coirt** [comment]
v2.3.0 available to build.

**Comment by pgatt** [comment]
Thanks!
