### ISSUE TITLE
Trim LFO Crushes Rack  2.0.4. VST and Stand alone

### ISSUE THREAD

**Issue by GenCode00** [Coirt/Bark#36]
if i turn down Offset 1 or offsest 2 knob  below -9 .4528 crushes both stand alone and vst rack on mac

**Comment by Coirt** [comment]
Looks like I reintroduced an old bug, hopefully next update fixed the issue. Let me know if it is not fixed but please supply the log file if it is not fixed.

**Comment by GenCode00** [comment]
Thx for Heads up. most certainly will
 do
________________________________

**Comment by Coirt** [comment]
Hopefully issue is fixed now, let me know if still present.

**Comment by Coirt** [comment]
Left guessing, closing.
