### ISSUE TITLE
Versions in your README.md, MakeFile and Bark.cpp

### ISSUE THREAD

**Issue by DomiKamu** [Coirt/Bark#4]
Hi, first thanks a lot for your Bark modules (I've compiled them myself for Windows, because I was not sure the fix indicated by Sebastien Bouffier - Gain.cpp - was applied (or not) in released binaries.

If you permit me, two recommendations:

1/ IMO it's not a good idea to indicate "your internal versions" of modules, such 0.0.3 for Gain (and so on) in your published README.md, because it may very confusing for community (however, you can use a separate text file - keept as "internal" - used as changelog/todo/reminder), it's better to use the same unified version number of all modules (such 0.5.1 in this case, currently indicated into your MakeFile) for each plugin. Also, showing v0.0.3, v0 or v0.0.1 to "public" doesn't look "professional" (trust me).

2/ It's a good idea, (IMO, again ;) to include the version number indicated into your *MakeFile* (you can modify it in order to plan an update, for example).

Example, from *Bark.cpp*, the main C++ source of your plugin, it may look like this (bold section):

void init(rack::Plugin *p) {
	plugin = p;
...
	p->slug = "Bark";
**#ifdef VERSION
	p->version = TOSTRING(VERSION);
#endif**
...

VERSION must be indicated in capital letters (case is sensitive). By doing this, the current version (the compiler takes version number from MakeFile) will be displayed from modules menu, when the mouse cursor "flies over" one of your module's name (in Bark manufacturer), this tip permits for any user to follow version of your plugin, and to update it when required (when you release an update). Don't worry if a certain module remains unchanged across consecutive updates! For Rack v0.5.1, as indicated in Rack's FAQ, it's recommended to use 0.5.x / 0.5.x.x for plugin's version.

In your case, **Bark v0.5.1** will be displayed in the modules menu. Please notice the letter "v" for version is automatically added when you compile your plugin, so never use "v" letter in your MakeFile!

Don't hesitate to contact me, as reply here or on my GitHub (send me a new issue) in case these explanations aren't clear ;) or if you've question.

I don't know if you're experimented developer, or not, but it's the goal of our community, to help us, when required. It's my state of mind, same also for many VCV Rack users (my cool guys). My name is Dominique (I'm French). I'm not C++ developer (I've started Jan 31st) but, fortunately, having long experience about software development (Delphi in particular, oriented-object Pascal language, very similar concepts against C++, so it was not too hard for me to go to VCV Rack development).

Regards.
Sorry for multiple edits, and sorry too if TLTR :)

**Comment by Coirt** [comment]
Hi Domi Thanks for looking out. Will do this when out of Beta.

**Comment by DomiKamu** [comment]
Hi Phil, fine! don't hesitate (I close this issue).
