### ISSUE TITLE
0.6.2 Update?

### ISSUE THREAD

**Issue by SteveRussell33** [Coirt/Bark#6]
Do you plan to update this for the latest VCV version?

Thanks

**Comment by Coirt** [comment]
@SteveRussell33 I do plan on getting back into development, took a break from rack to learn how to actually code as opposed to winging it.

Going to say February!

Apologies for the late reply.

**Comment by SteveRussell33** [comment]
No worries, thanks for the reply.

I'm doing the same, learning some C++ so I can finally get to work on some modules of my own, having learnt the basics from looking at other code.

Kind Regards
Steve

**Comment by Coirt** [comment]
@SteveRussell33 v0.6.2c is available for windows.

https://github.com/Coirt/Bark/files/2803938/Bark-0.6.2-win.zip

**Comment by SteveRussell33** [comment]
Thanks for the build zip. Appreciated. Will test at the weekend.

**Comment by Coirt** [comment]
No problem. If you find any problems just make a new issue, closing.
