### ISSUE TITLE
Unofficial Linux Build

### ISSUE THREAD

**Issue by Skrylar** [Coirt/Bark#8]
From OpenSuSE Tumbleweed, built against Rack masters.

[Bark-0.6.2-lin.zip](https://github.com/Coirt/Bark/files/2805907/Bark-0.6.2-lin.zip)

**Comment by Coirt** [comment]
Is this the from the merge?

**Comment by Coirt** [comment]
Cheers @Skrylar

**Comment by Coirt** [comment]
v0.6.3 now on plugin manager!
